'use strict';

/*
|--------------------------------------------------------------------------
| CompanySeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Database = use('Database');

class CompanySeeder {
  static async run() {
    const data = [
      {
        id: 20,
        name: 'Phoenix Restoration and Construction, Ltd',
        industry_id: 1,
        recruiter_id: 1,
        address_id: 5,
        contact_id: 5,
        email: 'mail20@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 21,
        name: 'Brehm Havel & Company, L.L.P.',
        industry_id: 2,
        recruiter_id: 2,
        address_id: 5,
        contact_id: 100,
        email: 'mail21@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 22,
        name: 'Fox Enterprises',
        industry_id: 3,
        recruiter_id: 3,
        address_id: 5,
        contact_id: 5,
        email: 'mail22@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 23,
        name: 'Landye Bennett Blumstein, LLP',
        industry_id: 4,
        recruiter_id: 4,
        address_id: 5,
        contact_id: 100,
        email: 'mail23@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 24,
        name: 'Lidel Construction',
        industry_id: 5,
        recruiter_id: 5,
        address_id: 5,
        contact_id: 5,
        email: 'mail24@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 25,
        name: 'Corbis Studio',
        industry_id: 6,
        recruiter_id: 6,
        address_id: 5,
        contact_id: 100,
        email: 'mail25@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 26,
        name: 'CHS Northern Plains',
        industry_id: 7,
        recruiter_id: 7,
        address_id: 5,
        contact_id: 5,
        email: 'mail26@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 27,
        name: 'Geroge-McKenna Electrical Contractors, Inc',
        industry_id: 8,
        recruiter_id: 8,
        address_id: 5,
        contact_id: 100,
        email: 'mail27@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 28,
        name: 'MD Home Health/MD Home Assist',
        industry_id: 9,
        recruiter_id: 9,
        address_id: 5,
        contact_id: 5,
        email: 'mail28@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 29,
        name: 'The James Group, LLC',
        industry_id: 10,
        recruiter_id: 10,
        address_id: 5,
        contact_id: 100,
        email: 'mail29@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 30,
        name: 'Quality Energy Service, Inc',
        industry_id: 11,
        recruiter_id: 11,
        address_id: 5,
        contact_id: 5,
        email: 'mail30@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 31,
        name: 'Siana Bellwoar Attorneys at Law',
        industry_id: 12,
        recruiter_id: 12,
        address_id: 5,
        contact_id: 100,
        email: 'mail31@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 32,
        name: 'PB + DC',
        industry_id: 13,
        recruiter_id: 13,
        address_id: 5,
        contact_id: 5,
        email: 'mail32@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 33,
        name: 'Beryy Home Centers, Inc',
        industry_id: 14,
        recruiter_id: 14,
        address_id: 5,
        contact_id: 100,
        email: 'mail33@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 34,
        name: 'AJ Lysne Contracting Corporation',
        industry_id: 15,
        recruiter_id: 15,
        address_id: 5,
        contact_id: 5,
        email: 'mail34@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 35,
        name: 'Key Logistics Solutions, LLC',
        industry_id: 16,
        recruiter_id: 16,
        address_id: 5,
        contact_id: 100,
        email: 'mail35@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 36,
        name: 'Homewood Building Supply, Inc',
        industry_id: 17,
        recruiter_id: 17,
        address_id: 5,
        contact_id: 5,
        email: 'mail36@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 37,
        name: 'Riverview Credit Union',
        industry_id: 18,
        recruiter_id: 18,
        address_id: 5,
        contact_id: 100,
        email: 'mail37@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 38,
        name: 'Betaseed',
        industry_id: 19,
        recruiter_id: 19,
        address_id: 5,
        contact_id: 5,
        email: 'mail38@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 39,
        name: 'Charles Cinvent George Design Group, Inc',
        industry_id: 20,
        recruiter_id: 20,
        address_id: 5,
        contact_id: 100,
        email: 'mail39@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 40,
        name: 'Crone Law Group',
        industry_id: 1,
        recruiter_id: 21,
        address_id: 5,
        contact_id: 5,
        email: 'mail40@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 41,
        name: 'WSW CPAs, PLLC',
        industry_id: 2,
        recruiter_id: 22,
        address_id: 5,
        contact_id: 100,
        email: 'mail41@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 42,
        name: 'Rectrix Aviation, Inc',
        industry_id: 3,
        recruiter_id: 23,
        address_id: 5,
        contact_id: 5,
        email: 'mail42@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 43,
        name: 'Weil Construction',
        industry_id: 4,
        recruiter_id: 24,
        address_id: 5,
        contact_id: 100,
        email: 'mail43@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 44,
        name: 'Clearwater COnstruction, Inc',
        industry_id: 5,
        recruiter_id: 25,
        address_id: 5,
        contact_id: 5,
        email: 'mail44@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 45,
        name: 'WaveGuide Corporation',
        industry_id: 6,
        recruiter_id: 26,
        address_id: 5,
        contact_id: 100,
        email: 'mail45@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 46,
        name: 'Reading Bakery Systems',
        industry_id: 7,
        recruiter_id: 27,
        address_id: 5,
        contact_id: 5,
        email: 'mail46@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 47,
        name: 'Greyhawk Construction',
        industry_id: 8,
        recruiter_id: 28,
        address_id: 5,
        contact_id: 100,
        email: 'mail47@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 48,
        name: 'Dahlin Group, Inc',
        industry_id: 9,
        recruiter_id: 29,
        address_id: 5,
        contact_id: 5,
        email: 'mail48@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 49,
        name: 'Amware',
        industry_id: 10,
        recruiter_id: 30,
        address_id: 5,
        contact_id: 100,
        email: 'mail49@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 50,
        name: 'AgLand Cooperative',
        industry_id: 11,
        recruiter_id: 31,
        address_id: 5,
        contact_id: 5,
        email: 'mail50@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 51,
        name: 'Brandeis Machinery & Supply',
        industry_id: 12,
        recruiter_id: 32,
        address_id: 5,
        contact_id: 100,
        email: 'mail51@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 52,
        name: 'Century Bank',
        industry_id: 13,
        recruiter_id: 33,
        address_id: 5,
        contact_id: 5,
        email: 'mail52@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 53,
        name: 'Roof Repair Specialist',
        industry_id: 14,
        recruiter_id: 34,
        address_id: 5,
        contact_id: 100,
        email: 'mail53@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 54,
        name: 'Civil & Environmental Consulatnats, Inc',
        industry_id: 15,
        recruiter_id: 35,
        address_id: 5,
        contact_id: 5,
        email: 'mail54@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 55,
        name: 'Comtech International Design Group',
        industry_id: 16,
        recruiter_id: 36,
        address_id: 5,
        contact_id: 100,
        email: 'mail55@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 56,
        name: 'Logansport Memorial Hospital',
        industry_id: 17,
        recruiter_id: 37,
        address_id: 5,
        contact_id: 5,
        email: 'mail56@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 57,
        name: 'Infrastructure Services',
        industry_id: 18,
        recruiter_id: 38,
        address_id: 5,
        contact_id: 100,
        email: 'mail57@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 58,
        name: 'Expanded Solutions, LLC',
        industry_id: 19,
        recruiter_id: 39,
        address_id: 5,
        contact_id: 5,
        email: 'mail58@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 59,
        name: 'Augustine Builders',
        industry_id: 20,
        recruiter_id: 40,
        address_id: 5,
        contact_id: 100,
        email: 'mail59@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 60,
        name: 'Farmers Union Coop',
        industry_id: 21,
        recruiter_id: 41,
        address_id: 5,
        contact_id: 5,
        email: 'mail60@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 61,
        name: 'Restorations Unlimited, LLC',
        industry_id: 22,
        recruiter_id: 42,
        address_id: 5,
        contact_id: 100,
        email: 'mail61@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 62,
        name: 'Roadrunner Restoration',
        industry_id: 23,
        recruiter_id: 43,
        address_id: 5,
        contact_id: 5,
        email: 'mail62@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 63,
        name: 'Charlotte Paint Company, Inc',
        industry_id: 24,
        recruiter_id: 44,
        address_id: 5,
        contact_id: 100,
        email: 'mail63@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 64,
        name: 'Climate Control Company',
        industry_id: 25,
        recruiter_id: 45,
        address_id: 5,
        contact_id: 5,
        email: 'mail64@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 65,
        name: 'Opto Tree',
        industry_id: 26,
        recruiter_id: 46,
        address_id: 5,
        contact_id: 100,
        email: 'mail65@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 66,
        name: 'Midwestern Pet Foods, Inc',
        industry_id: 27,
        recruiter_id: 47,
        address_id: 5,
        contact_id: 5,
        email: 'mail66@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 67,
        name: 'Bodines Landscape Services, Inc',
        industry_id: 28,
        recruiter_id: 48,
        address_id: 5,
        contact_id: 100,
        email: 'mail67@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 68,
        name: 'Dixieline Lumber Company',
        industry_id: 29,
        recruiter_id: 49,
        address_id: 5,
        contact_id: 5,
        email: 'mail68@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 69,
        name: 'Nabholz Construction',
        industry_id: 30,
        recruiter_id: 50,
        address_id: 5,
        contact_id: 100,
        email: 'mail69@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 70,
        name: 'Arboles NC INC',
        industry_id: 20,
        recruiter_id: 51,
        address_id: 5,
        contact_id: 5,
        email: 'mail70@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 71,
        name: 'Brothers Electric',
        industry_id: 21,
        recruiter_id: 52,
        address_id: 5,
        contact_id: 100,
        email: 'mail71@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 72,
        name: 'MacQueen Equipment',
        industry_id: 22,
        recruiter_id: 53,
        address_id: 5,
        contact_id: 5,
        email: 'mail72@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 73,
        name: 'Texas Home Performance',
        industry_id: 23,
        recruiter_id: 54,
        address_id: 5,
        contact_id: 100,
        email: 'mail73@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 74,
        name: 'Burdette, Koehler, Murphy & Associates, Inc',
        industry_id: 24,
        recruiter_id: 55,
        address_id: 5,
        contact_id: 5,
        email: 'mail74@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 75,
        name: 'Million Air',
        industry_id: 25,
        recruiter_id: 56,
        address_id: 5,
        contact_id: 100,
        email: 'mail75@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 76,
        name: 'Stinson, LLP',
        industry_id: 26,
        recruiter_id: 57,
        address_id: 5,
        contact_id: 5,
        email: 'mail76@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 77,
        name: 'KCA Engineers, Inc',
        industry_id: 27,
        recruiter_id: 1,
        address_id: 5,
        contact_id: 100,
        email: 'mail77@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 78,
        name: 'Neptune Plumbing & Heating, Co',
        industry_id: 28,
        recruiter_id: 2,
        address_id: 5,
        contact_id: 5,
        email: 'mail78@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 79,
        name: 'Homewood Insurance Agency',
        industry_id: 29,
        recruiter_id: 3,
        address_id: 5,
        contact_id: 100,
        email: 'mail79@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 80,
        name: 'AHT Insurance',
        industry_id: 30,
        recruiter_id: 4,
        address_id: 5,
        contact_id: 5,
        email: 'mail80@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 81,
        name: 'Kier & Wright',
        industry_id: 1,
        recruiter_id: 5,
        address_id: 5,
        contact_id: 100,
        email: 'mail81@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 82,
        name: 'CMBG3 Law, LLC',
        industry_id: 2,
        recruiter_id: 6,
        address_id: 5,
        contact_id: 5,
        email: 'mail82@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 83,
        name: 'McDonough Marine Service',
        industry_id: 3,
        recruiter_id: 7,
        address_id: 5,
        contact_id: 100,
        email: 'mail83@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 84,
        name: 'Celtic Marine Corporation',
        industry_id: 4,
        recruiter_id: 8,
        address_id: 5,
        contact_id: 5,
        email: 'mail84@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 85,
        name: 'American International Contractors',
        industry_id: 5,
        recruiter_id: 9,
        address_id: 5,
        contact_id: 100,
        email: 'mail85@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 86,
        name: 'ProVen Pharmaceuticals, LLC',
        industry_id: 6,
        recruiter_id: 10,
        address_id: 5,
        contact_id: 5,
        email: 'mail86@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 87,
        name: 'Think Architecture, Inc',
        industry_id: 7,
        recruiter_id: 11,
        address_id: 5,
        contact_id: 100,
        email: 'mail87@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 88,
        name: 'Shea, Inc',
        industry_id: 8,
        recruiter_id: 12,
        address_id: 5,
        contact_id: 5,
        email: 'mail88@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 89,
        name: 'CCS Consultants, Inc',
        industry_id: 9,
        recruiter_id: 13,
        address_id: 5,
        contact_id: 100,
        email: 'mail89@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 90,
        name: 'Partners Risk Services',
        industry_id: 10,
        recruiter_id: 14,
        address_id: 5,
        contact_id: 5,
        email: 'mail90@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 91,
        name: 'Best Logistics Group',
        industry_id: 11,
        recruiter_id: 15,
        address_id: 5,
        contact_id: 100,
        email: 'mail91@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 92,
        name: 'EED',
        industry_id: 12,
        recruiter_id: 16,
        address_id: 5,
        contact_id: 5,
        email: 'mail92@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 93,
        name: 'Hub International Limited',
        industry_id: 13,
        recruiter_id: 17,
        address_id: 5,
        contact_id: 100,
        email: 'mail93@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 94,
        name: 'Power and Rubber Supply',
        industry_id: 14,
        recruiter_id: 18,
        address_id: 5,
        contact_id: 5,
        email: 'mail94@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 95,
        name: 'Kutak Rock, LLP',
        industry_id: 15,
        recruiter_id: 19,
        address_id: 5,
        contact_id: 100,
        email: 'mail95@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 96,
        name: 'R.A. Smith National, Inc',
        industry_id: 16,
        recruiter_id: 20,
        address_id: 5,
        contact_id: 5,
        email: 'mail96@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 97,
        name: 'Bruce Dees & Associates',
        industry_id: 17,
        recruiter_id: 21,
        address_id: 5,
        contact_id: 100,
        email: 'mail97@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 98,
        name: 'Robinson Brog Leinwand Greene Genovese & Bluck',
        industry_id: 18,
        recruiter_id: 22,
        address_id: 5,
        contact_id: 5,
        email: 'mail98@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 99,
        name: 'Haila Architecture | Structure | Planning Ltd',
        industry_id: 19,
        recruiter_id: 23,
        address_id: 5,
        contact_id: 100,
        email: 'mail99@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 100,
        name: 'Hirschi Roofing and Insulation',
        industry_id: 20,
        recruiter_id: 24,
        address_id: 5,
        contact_id: 5,
        email: 'mail100@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 101,
        name: 'Collin Bryan Construction',
        industry_id: 1,
        recruiter_id: 25,
        address_id: 5,
        contact_id: 100,
        email: 'mail101@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 102,
        name: 'Kuck Mechanical',
        industry_id: 2,
        recruiter_id: 10,
        address_id: 5,
        contact_id: 5,
        email: 'mail102@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 103,
        name: 'Griffith, Lerman, Lutz & Scheib',
        industry_id: 3,
        recruiter_id: 11,
        address_id: 5,
        contact_id: 100,
        email: 'mail103@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 104,
        name: 'Marker Therapeutics, Inc',
        industry_id: 4,
        recruiter_id: 12,
        address_id: 5,
        contact_id: 5,
        email: 'mail104@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 105,
        name: 'Punt Enterprises',
        industry_id: 5,
        recruiter_id: 13,
        address_id: 5,
        contact_id: 100,
        email: 'mail105@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 106,
        name: 'ExcelAg Corp',
        industry_id: 6,
        recruiter_id: 14,
        address_id: 5,
        contact_id: 5,
        email: 'mail106@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 107,
        name: 'Impact Landscapes, LLC',
        industry_id: 7,
        recruiter_id: 15,
        address_id: 5,
        contact_id: 100,
        email: 'mail107@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 108,
        name: 'Marex Services, LLC',
        industry_id: 8,
        recruiter_id: 16,
        address_id: 5,
        contact_id: 5,
        email: 'mail108@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 109,
        name: 'System Mechanical and Safety Solutions',
        industry_id: 9,
        recruiter_id: 17,
        address_id: 5,
        contact_id: 100,
        email: 'mail109@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 110,
        name: 'Flower Turbines, LLC',
        industry_id: 10,
        recruiter_id: 18,
        address_id: 5,
        contact_id: 5,
        email: 'mail110@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 111,
        name: 'Margoulis Edelstein',
        industry_id: 11,
        recruiter_id: 19,
        address_id: 5,
        contact_id: 100,
        email: 'mail111@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 112,
        name: 'Law, LLC',
        industry_id: 12,
        recruiter_id: 20,
        address_id: 5,
        contact_id: 5,
        email: 'mail112@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 113,
        name: 'A & E Construction Supply, Inc',
        industry_id: 13,
        recruiter_id: 21,
        address_id: 5,
        contact_id: 100,
        email: 'mail113@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 114,
        name: 'W.W. Clyde & Co.',
        industry_id: 14,
        recruiter_id: 22,
        address_id: 5,
        contact_id: 5,
        email: 'mail114@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 115,
        name: 'Hiller Plumbing',
        industry_id: 15,
        recruiter_id: 23,
        address_id: 5,
        contact_id: 100,
        email: 'mail115@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 116,
        name: 'Hainer & Berman, P.C.',
        industry_id: 16,
        recruiter_id: 24,
        address_id: 5,
        contact_id: 5,
        email: 'mail116@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 117,
        name: 'Foundation Risk Partners dba Pinnacle Brokers Insurance Solutions',
        industry_id: 17,
        recruiter_id: 25,
        address_id: 5,
        contact_id: 100,
        email: 'mail117@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 118,
        name: 'Eagle Pipe Heating & Air',
        industry_id: 18,
        recruiter_id: 26,
        address_id: 5,
        contact_id: 5,
        email: 'mail118@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 119,
        name: 'Electric Plus, Inc',
        industry_id: 19,
        recruiter_id: 27,
        address_id: 5,
        contact_id: 100,
        email: 'mail119@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 120,
        name: 'Interplan, LLC',
        industry_id: 20,
        recruiter_id: 28,
        address_id: 5,
        contact_id: 5,
        email: 'mail120@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 121,
        name: 'Convexity Scientific',
        industry_id: 1,
        recruiter_id: 29,
        address_id: 5,
        contact_id: 100,
        email: 'mail121@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 122,
        name: 'Blazer Industries, Inc',
        industry_id: 2,
        recruiter_id: 30,
        address_id: 5,
        contact_id: 5,
        email: 'mail122@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 123,
        name: 'Clearview Land Design',
        industry_id: 3,
        recruiter_id: 31,
        address_id: 5,
        contact_id: 100,
        email: 'mail123@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 124,
        name: 'Axia Insurance Services, Inc',
        industry_id: 4,
        recruiter_id: 32,
        address_id: 5,
        contact_id: 5,
        email: 'mail124@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 125,
        name: "Yoder's Building Supply",
        industry_id: 5,
        recruiter_id: 33,
        address_id: 5,
        contact_id: 100,
        email: 'mail125@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 126,
        name: 'Wyatt Tarrant & Combs, LLP',
        industry_id: 6,
        recruiter_id: 34,
        address_id: 5,
        contact_id: 5,
        email: 'mail126@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 127,
        name: 'Sterling Crane pty, Ltd.',
        industry_id: 7,
        recruiter_id: 35,
        address_id: 5,
        contact_id: 100,
        email: 'mail127@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 128,
        name: 'Shrewsberry and Associates',
        industry_id: 8,
        recruiter_id: 36,
        address_id: 5,
        contact_id: 5,
        email: 'mail128@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 129,
        name: 'Kapnick Insurance Group',
        industry_id: 9,
        recruiter_id: 37,
        address_id: 5,
        contact_id: 100,
        email: 'mail129@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 130,
        name: 'TPC Mechanical Contractors',
        industry_id: 10,
        recruiter_id: 38,
        address_id: 5,
        contact_id: 5,
        email: 'mail130@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 131,
        name: 'Dorvin D. Leis co, Inc',
        industry_id: 11,
        recruiter_id: 39,
        address_id: 5,
        contact_id: 100,
        email: 'mail131@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 132,
        name: 'Craig Farmers Cooperative Company',
        industry_id: 12,
        recruiter_id: 40,
        address_id: 5,
        contact_id: 5,
        email: 'mail132@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 133,
        name: 'Aria Nursing & Rehab',
        industry_id: 13,
        recruiter_id: 41,
        address_id: 5,
        contact_id: 100,
        email: 'mail133@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 134,
        name: 'Helix Electric, Inc',
        industry_id: 14,
        recruiter_id: 42,
        address_id: 5,
        contact_id: 5,
        email: 'mail134@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 135,
        name: 'HMH Engineers',
        industry_id: 15,
        recruiter_id: 43,
        address_id: 5,
        contact_id: 100,
        email: 'mail135@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 136,
        name: 'Greenwood & Moore, Inc',
        industry_id: 16,
        recruiter_id: 44,
        address_id: 5,
        contact_id: 5,
        email: 'mail136@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 137,
        name: 'Carson McElheney',
        industry_id: 17,
        recruiter_id: 45,
        address_id: 5,
        contact_id: 100,
        email: 'mail137@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 138,
        name: 'Northstar Systembuilt LLC',
        industry_id: 18,
        recruiter_id: 1,
        address_id: 5,
        contact_id: 5,
        email: 'mail138@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 139,
        name: 'National HVAC Service, LLC',
        industry_id: 19,
        recruiter_id: 2,
        address_id: 5,
        contact_id: 100,
        email: 'mail139@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 140,
        name: 'Chapman Law Group',
        industry_id: 20,
        recruiter_id: 3,
        address_id: 5,
        contact_id: 5,
        email: 'mail140@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 141,
        name: 'Lano Equipment Inc',
        industry_id: 21,
        recruiter_id: 4,
        address_id: 5,
        contact_id: 100,
        email: 'mail141@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 142,
        name: "Bart's Electric Company",
        industry_id: 22,
        recruiter_id: 5,
        address_id: 5,
        contact_id: 5,
        email: 'mail142@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 143,
        name: 'Baker Roofing',
        industry_id: 23,
        recruiter_id: 6,
        address_id: 5,
        contact_id: 100,
        email: 'mail143@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 144,
        name: 'Home Care Assistance of Naples',
        industry_id: 24,
        recruiter_id: 7,
        address_id: 5,
        contact_id: 5,
        email: 'mail144@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 145,
        name: 'Eclat Roofing',
        industry_id: 25,
        recruiter_id: 8,
        address_id: 5,
        contact_id: 100,
        email: 'mail145@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 146,
        name: 'Evans & Dixon L.L.C',
        industry_id: 26,
        recruiter_id: 9,
        address_id: 5,
        contact_id: 5,
        email: 'mail146@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 147,
        name: 'Kelly Aerospace Energy Systems LLC',
        industry_id: 27,
        recruiter_id: 10,
        address_id: 5,
        contact_id: 100,
        email: 'mail147@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 148,
        name: 'Standard Industrial Corp.',
        industry_id: 28,
        recruiter_id: 11,
        address_id: 5,
        contact_id: 5,
        email: 'mail148@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 149,
        name: 'Neal Electric Corp.',
        industry_id: 29,
        recruiter_id: 12,
        address_id: 5,
        contact_id: 100,
        email: 'mail149@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 150,
        name: 'Precise Heating & Cooling LLC',
        industry_id: 30,
        recruiter_id: 13,
        address_id: 5,
        contact_id: 5,
        email: 'mail150@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 151,
        name: 'M Designs Architects, Inc.',
        industry_id: 21,
        recruiter_id: 14,
        address_id: 5,
        contact_id: 100,
        email: 'mail151@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 152,
        name: 'RA Yancey Lumber Corporation',
        industry_id: 22,
        recruiter_id: 15,
        address_id: 5,
        contact_id: 5,
        email: 'mail152@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 153,
        name: 'JH Roofing Inc',
        industry_id: 23,
        recruiter_id: 16,
        address_id: 5,
        contact_id: 100,
        email: 'mail153@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 154,
        name: 'Strategic Builders',
        industry_id: 24,
        recruiter_id: 17,
        address_id: 5,
        contact_id: 5,
        email: 'mail154@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 155,
        name: 'Alliance Mechanical Services',
        industry_id: 25,
        recruiter_id: 18,
        address_id: 5,
        contact_id: 100,
        email: 'mail155@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 156,
        name: 'SmartFlow Technologies Inc',
        industry_id: 26,
        recruiter_id: 19,
        address_id: 5,
        contact_id: 5,
        email: 'mail156@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 157,
        name: 'Poepping, Stone, Bach & Associates, Inc.',
        industry_id: 27,
        recruiter_id: 20,
        address_id: 5,
        contact_id: 100,
        email: 'mail157@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 158,
        name: 'First Financial Northwest Bank',
        industry_id: 28,
        recruiter_id: 21,
        address_id: 5,
        contact_id: 5,
        email: 'mail158@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 159,
        name: 'RAPiD Genomics LLC',
        industry_id: 29,
        recruiter_id: 22,
        address_id: 5,
        contact_id: 100,
        email: 'mail159@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 160,
        name: 'GeoPoint Surveying',
        industry_id: 30,
        recruiter_id: 23,
        address_id: 5,
        contact_id: 5,
        email: 'mail160@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 161,
        name: 'North American Mechanical/ Comfort Systems USA',
        industry_id: 1,
        recruiter_id: 24,
        address_id: 5,
        contact_id: 100,
        email: 'mail161@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 162,
        name: 'K2 Electric',
        industry_id: 2,
        recruiter_id: 25,
        address_id: 5,
        contact_id: 5,
        email: 'mail162@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 163,
        name: 'Centric Architecture Inc',
        industry_id: 3,
        recruiter_id: 26,
        address_id: 5,
        contact_id: 100,
        email: 'mail163@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 164,
        name: 'Bergman, Walls & Associates',
        industry_id: 4,
        recruiter_id: 27,
        address_id: 5,
        contact_id: 5,
        email: 'mail164@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 165,
        name: 'Freight All Kinds Inc',
        industry_id: 5,
        recruiter_id: 28,
        address_id: 5,
        contact_id: 100,
        email: 'mail165@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 166,
        name: 'Agrisource Inc',
        industry_id: 6,
        recruiter_id: 29,
        address_id: 5,
        contact_id: 5,
        email: 'mail166@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 167,
        name: 'Shaw Electric Company',
        industry_id: 7,
        recruiter_id: 30,
        address_id: 5,
        contact_id: 100,
        email: 'mail167@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 168,
        name: 'MacBeath Hardwood',
        industry_id: 8,
        recruiter_id: 31,
        address_id: 5,
        contact_id: 5,
        email: 'mail168@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 169,
        name: 'BGW CPA, PLLC',
        industry_id: 9,
        recruiter_id: 32,
        address_id: 5,
        contact_id: 100,
        email: 'mail169@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 170,
        name: 'Brad Smith Roofing Co., Inc.',
        industry_id: 10,
        recruiter_id: 33,
        address_id: 5,
        contact_id: 5,
        email: 'mail170@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 171,
        name: 'Hatzel & Buehler Inc',
        industry_id: 11,
        recruiter_id: 34,
        address_id: 5,
        contact_id: 100,
        email: 'mail171@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 172,
        name: 'George F. Young',
        industry_id: 12,
        recruiter_id: 35,
        address_id: 5,
        contact_id: 5,
        email: 'mail172@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 173,
        name: 'Manko Gold Katcher & Fox LLP',
        industry_id: 13,
        recruiter_id: 36,
        address_id: 5,
        contact_id: 100,
        email: 'mail173@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 174,
        name: 'Aero Air LLC',
        industry_id: 14,
        recruiter_id: 37,
        address_id: 5,
        contact_id: 5,
        email: 'mail174@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 175,
        name: 'Stratton Equity Coop',
        industry_id: 15,
        recruiter_id: 38,
        address_id: 5,
        contact_id: 100,
        email: 'mail175@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 176,
        name: 'SFC Engineering Partnership, Inc',
        industry_id: 16,
        recruiter_id: 39,
        address_id: 5,
        contact_id: 5,
        email: 'mail176@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 177,
        name: 'CKH CPA',
        industry_id: 17,
        recruiter_id: 40,
        address_id: 5,
        contact_id: 100,
        email: 'mail177@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 178,
        name: 'Team Select Home Care',
        industry_id: 18,
        recruiter_id: 41,
        address_id: 5,
        contact_id: 5,
        email: 'mail178@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 179,
        name: 'Van Valer Law Firm LLP',
        industry_id: 19,
        recruiter_id: 42,
        address_id: 5,
        contact_id: 100,
        email: 'mail179@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 180,
        name: 'List Engineering Company, Inc.',
        industry_id: 20,
        recruiter_id: 43,
        address_id: 5,
        contact_id: 5,
        email: 'mail180@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 181,
        name: 'Smith Gee Studio',
        industry_id: 21,
        recruiter_id: 44,
        address_id: 5,
        contact_id: 5,
        email: 'mail181@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 182,
        name: 'HKC Roofing & Sheet Metal',
        industry_id: 22,
        recruiter_id: 45,
        address_id: 5,
        contact_id: 5,
        email: 'mail182@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 183,
        name: 'TSA Architects',
        industry_id: 23,
        recruiter_id: 46,
        address_id: 5,
        contact_id: 5,
        email: 'mail183@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 184,
        name: 'Hidden Creek Landscaping',
        industry_id: 24,
        recruiter_id: 47,
        address_id: 5,
        contact_id: 5,
        email: 'mail184@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      },
      {
        id: 185,
        name: 'Freight Services',
        industry_id: 25,
        recruiter_id: 48,
        address_id: 5,
        contact_id: 5,
        email: 'mail185@gpac.com',
        link_profile: 'http://linkedin.com',
        website: 'http://www.site.com'
      }
    ];
    await Database.table('companies').insert(data)
    await Database.raw("SELECT setval('companies_id_seq',?, true)",[data.length])
  }
}

module.exports = CompanySeeder;
