# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: CmdLine@2
  displayName: "Running tests"
  inputs:
    script: |      
      npm run testci

- task: PublishTestResults@2
  displayName: "Publish Test Results"
  inputs:
    testResultsFiles: test-result-junit.xml
    testResultsFormat: 'JUnit'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy to release'
  inputs:
    SourceFolder: $(System.DefaultWorkingDirectory) 
    contents: |
      **/*
      !.git/**/*
    targetFolder: '$(System.DefaultWorkingDirectory)/release'

- task: ArchiveFiles@2
  displayName: "Archiving build"
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true    

- task: PublishBuildArtifacts@1
  condition: succeeded()
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'



